services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.simple
      args:
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        - GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY}
    container_name: grip-investment-app
    ports:
      - "3000:3000"
    environment:
      # Runtime environment variables
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY}
    restart: unless-stopped
    networks:
      - grip-network

networks:
  grip-network:
    driver: bridge